### PR TITLE
Fix delete on mac

### PR DESCRIPTION
**Pull request by wrexbe**
Delete key on mac does backspace

### CODE REVIEW

**Comment by zHaytam** [comment]
Hey, thanks for the PR!

**Comment by wrexbe** [comment]
Yeah I didn't try building your example/test projects when I changed it, probably should fix those

**Comment by zHaytam** [comment]
I honestly think it's better if you target the branch **develop** for your PR, instead of master, so that your change is in version 3.0.0

**Comment by wrexbe** [comment]
Yeah I will fix it up later

**Comment by wrexbe** [comment]
Would you accept a PR to bump everything to .net 7, and update the nuggets?

**Comment by zHaytam** [comment]
> Would you accept a PR to bump everything to .net 7, and update the nuggets?

Unfortunately no, .NET 6 is LTS so I'm more comfortable targetting it for now.

**Comment by wrexbe** [comment]
Ok what about a PR to bump to 6 then?

**Comment by zHaytam** [comment]
Version 3, which is in beta, already targets .NET 6.  
Check out the branch develop.

**Pull request closed without merging**
