### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by Rickybarb5**
Added tests for most of the model logic.

### CODE REVIEW

**Comment by zHaytam** [comment]
Hello, thank you so much for the MR!  
I have a couple of questions if possible:

- Why did you create a separate project for Models? I believe it's better to have two projects, `Blazor.Diagrams.Core.Tests` (includes unit tests) and `Blazor.Diagrams.Tests` (includes bUnit tests).
- I never used this kind of way to test things (fixtures), what's the benefit of it? Do you have any article that I can read to better understand this approach?

There are some changes in 2.0.0 that will probably break this, but I'll handle them.

**Comment by Rickybarb5** [comment]
Hey there!

- I created two projects just due to the naming of the namespaces (it's how I usually do it it's perfectly fine if you want to join the two).

- Fixtures are used to separate testing logic from mocking, for example. It's basically a way to have more readable tests. In these test files each test has its own fixture, but xUnit has really cool features like shared fixtures for integration testing:
https://xunit.net/docs/shared-context

Fixtures are the standard way of unit testing these days( BTW I do agree bUnit tests should have their own project)

**Comment by zHaytam** [comment]
Yeah, I think it's better to join the projects.

From what I understood from fixtures, they are used to share context between multiple tests right? But in your tests, technically, the fixture will be created before each test no? So it's the same as setting up stuff in every test. Maybe fixtures are also used to only have to setup stuff once (in the fixture's constructor)?

Sorry for being this picky, just trying to understand this new approach!

**Comment by Rickybarb5** [comment]
Exactly, for each test, a fixture will be instantiated, which helps with isolation( you want that in unit testing). Maybe this will help you understand better:
https://medium.com/@tasdikrahman/f-i-r-s-t-principles-of-testing-1a497acda8d6
Fixtures can also contain mocked data/services and methods to instantiate them for general or specific test cases. If you don't know about mocking, check this out:
https://www.c-sharpcorner.com/article/moq-mocking-framework-with-xunit-net-testing-fr/

As for shared Fixtures, they are usually used for integration testing, an example would be instantiating an in-memory database for a test collection.

**Pull request closed without merging**
